version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.7
    environment:
      BUCKET: demo
      MINIO_STORAGE: https://storage.offen.dev
    working_directory: ~/offen
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy to S3
          command: |
            AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY aws --endpoint $MINIO_STORAGE s3 cp demo.sh s3://$BUCKET
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: AWS
          filters:
            branches:
              only:
                - master

orbs:
  aws-cli: circleci/aws-cli@1.1.0
